use super::*;
#[tokio::test]
async fn each_turn_carries_its_own_recorded_time() {
    let (server, clock) = born_agent();
    let leads = ConversationLocator::new(TEST_PLATFORM, "leads");
    let model = ScriptedModel::new([
        Completion::Reply("morning".to_owned()),
        Completion::Reply("still morning".to_owned()),
    ]);

    server
        .platform()
        .route_message(
            &model,
            &leads,
            &PersonId::new(TEST_PLATFORM, "dave"),
            "first message",
            &[PersonId::new(TEST_PLATFORM, "dave")],
        )
        .await
        .unwrap();
    // Ten minutes later, within the idle gap, so the same session continues and the buffer replays.
    clock.advance_millis(600 * 1_000);
    server
        .platform()
        .route_message(
            &model,
            &leads,
            &PersonId::new(TEST_PLATFORM, "dave"),
            "second message",
            &[PersonId::new(TEST_PLATFORM, "dave")],
        )
        .await
        .unwrap();

    // The second turn's prompt shows the first message frozen at its original time and the new inbound
    // at the advanced time — "now" tracks the clock without the historical stamp drifting.
    let seen = model.recorded_messages();
    let turn2: Vec<&str> = seen
        .last()
        .unwrap()
        .iter()
        .map(|message| message.content.as_str())
        .collect();
    assert_eq!(
        turn2,
        vec![
            "[Mon 2026-06-08 00:00 UTC] dave: first message",
            "morning",
            "[Mon 2026-06-08 00:10 UTC] dave: second message",
        ]
    );
}

#[tokio::test]
async fn a_substantive_session_flushes_to_memory_before_the_cut() {
    let (server, _clock) = born_agent();
    let mut settings = server.control().settings().unwrap();
    settings.compaction.token_budget = 100;
    // The default flush gate is four turns; the two exchanges below reach it.
    server.control().set_settings(settings).unwrap();

    let leads = ConversationLocator::new(TEST_PLATFORM, "leads");
    let model = ScriptedModel::with_usage([
        // Two ordinary exchanges build the session to four turns; the second crosses the budget.
        (Completion::Reply("ok one".to_owned()), 10),
        (Completion::Reply("ok two".to_owned()), 200),
        // The pre-compaction flush writes durable state, then confirms.
        (
            run_lua_call(r#"memory.create("topic/plan", "Decided to ship on Friday")"#),
            0,
        ),
        (Completion::Reply("flushed".to_owned()), 0),
        // Genesis registered the description-regen template, so the flushed memory is regenerated.
        (describe_call("The team's plan to ship on Friday."), 0),
    ]);

    server
        .platform()
        .route_message(
            &model,
            &leads,
            &PersonId::new(TEST_PLATFORM, "dave"),
            "morning",
            &[PersonId::new(TEST_PLATFORM, "dave")],
        )
        .await
        .unwrap();
    server
        .platform()
        .route_message(
            &model,
            &leads,
            &PersonId::new(TEST_PLATFORM, "dave"),
            "any updates",
            &[PersonId::new(TEST_PLATFORM, "dave")],
        )
        .await
        .unwrap();
    // The flush's writes are described off the hot path; drive the catch-up to regenerate them.
    server.describe_catch_up(&model).await.unwrap();

    // Only the flush calls run_lua here, so the memory's presence is the flush's signature — it wrote
    // the working state to memory, its description regenerated by the off-hot-path catch-up.
    let plan = server.control().memory("topic/plan").unwrap();
    assert!(plan.is_some());
    assert_eq!(
        plan.unwrap().description,
        "The team's plan to ship on Friday."
    );
}

#[tokio::test]
async fn a_low_activity_session_skips_the_flush() {
    let (server, _clock) = born_agent();
    let mut settings = server.control().settings().unwrap();
    settings.compaction.token_budget = 100;
    server.control().set_settings(settings).unwrap();

    let leads = ConversationLocator::new(TEST_PLATFORM, "leads");
    // A single exchange (two turns) crosses the budget — below the four-turn gate. Only the turn's
    // own response is scripted: were the flush to run, it would call the model again and exhaust the
    // queue, erroring. The route succeeding is what proves the flush was skipped.
    let model =
        ScriptedModel::with_usage([(Completion::Reply("a giant paste, noted".to_owned()), 500)]);

    server
        .platform()
        .route_message(
            &model,
            &leads,
            &PersonId::new(TEST_PLATFORM, "dave"),
            "<a huge paste>",
            &[PersonId::new(TEST_PLATFORM, "dave")],
        )
        .await
        .unwrap();

    // The session ended (a re-segment is staged) without a flush turn having run.
    assert_eq!(server.control().sessions(&leads).unwrap().len(), 1);
}

/// Point the checkpoint gates at a test's scale: a small substance threshold (30 chars — a one-line
/// greeting stays under it, a substantive message clears it) and no cooldown unless the test is about
/// it. Disables `flush_on_open` so these tests exercise the timer sweep in isolation: with it on, the
/// second room opening would itself checkpoint-flush the first (the substance-gated open trigger),
/// pre-empting the explicit sweep the tests drive.
pub(crate) fn tune_checkpoint(server: &Server, min_delta_chars: i64, cooldown_seconds: i64) {
    let mut settings = server.control().settings().unwrap();
    settings.checkpoint.min_delta_chars = min_delta_chars;
    settings.checkpoint.cooldown_seconds = cooldown_seconds;
    settings.checkpoint.flush_on_open = false;
    server.control().set_settings(settings).unwrap();
}

/// A substantive room-A message that clears a 30-char substance threshold.
pub(crate) const SUBSTANTIVE: &str = "We decided: the migration ships on Friday, Erin owns the comms, and \
                           the fallback window is Monday morning.";

#[tokio::test]
async fn a_checkpoint_fires_only_past_the_substance_threshold() {
    let (server, _clock) = born_agent();
    tune_checkpoint(&server, 200, 0);

    let room_a = ConversationLocator::new(TEST_PLATFORM, "room-a");
    let room_b = ConversationLocator::new(TEST_PLATFORM, "room-b");
    let model = ScriptedModel::new([
        Completion::Reply("ok".to_owned()),
        Completion::Reply("ok".to_owned()),
        Completion::Reply("noted the plan".to_owned()),
        // The one checkpoint flush at the end confirms.
        Completion::Reply("checkpointed".to_owned()),
    ]);
    server
        .platform()
        .route_message(
            &model,
            &room_a,
            &PersonId::new(TEST_PLATFORM, "dave"),
            "hi",
            &[PersonId::new(TEST_PLATFORM, "dave")],
        )
        .await
        .unwrap();
    server
        .platform()
        .route_message(
            &model,
            &room_b,
            &PersonId::new(TEST_PLATFORM, "erin"),
            "hello",
            &[PersonId::new(TEST_PLATFORM, "erin")],
        )
        .await
        .unwrap();

    // Cooldown passes (zero) and the audience is live (room B), but neither room's delta reaches the
    // threshold — the substance gate alone blocks.
    assert_eq!(
        server
            .checkpoint_live_sessions(&model, CheckpointTrigger::Timer)
            .await
            .unwrap(),
        0
    );

    // A substantive message pushes room A's delta past the threshold; the same sweep now flushes it.
    let long = SUBSTANTIVE.repeat(3);
    server
        .platform()
        .route_message(
            &model,
            &room_a,
            &PersonId::new(TEST_PLATFORM, "dave"),
            &long,
            &[PersonId::new(TEST_PLATFORM, "dave")],
        )
        .await
        .unwrap();
    assert_eq!(
        server
            .checkpoint_live_sessions(&model, CheckpointTrigger::Timer)
            .await
            .unwrap(),
        1
    );
}

#[tokio::test]
async fn a_checkpoint_waits_out_the_cooldown() {
    let (server, clock) = born_agent();
    tune_checkpoint(&server, 30, 600);

    let room_a = ConversationLocator::new(TEST_PLATFORM, "room-a");
    let room_b = ConversationLocator::new(TEST_PLATFORM, "room-b");
    let model = ScriptedModel::new([
        Completion::Reply("noted".to_owned()),
        Completion::Reply("ok".to_owned()),
        Completion::Reply("checkpointed".to_owned()),
    ]);
    server
        .platform()
        .route_message(
            &model,
            &room_a,
            &PersonId::new(TEST_PLATFORM, "dave"),
            SUBSTANTIVE,
            &[PersonId::new(TEST_PLATFORM, "dave")],
        )
        .await
        .unwrap();
    server
        .platform()
        .route_message(
            &model,
            &room_b,
            &PersonId::new(TEST_PLATFORM, "erin"),
            "hi",
            &[PersonId::new(TEST_PLATFORM, "erin")],
        )
        .await
        .unwrap();

    // Substance and audience pass, but the session is younger than the cooldown (measured from its
    // start, since it has never flushed) — the cooldown gate alone blocks.
    assert_eq!(
        server
            .checkpoint_live_sessions(&model, CheckpointTrigger::Timer)
            .await
            .unwrap(),
        0
    );

    // Past the cooldown (still within the idle gap), the sweep flushes room A. Room B's delta stays
    // under the substance threshold, so it does not ride along.
    clock.advance_millis(601 * 1_000);
    assert_eq!(
        server
            .checkpoint_live_sessions(&model, CheckpointTrigger::Timer)
            .await
            .unwrap(),
        1
    );
}

#[tokio::test]
async fn a_checkpoint_requires_a_live_audience() {
    let (server, _clock) = born_agent();
    tune_checkpoint(&server, 30, 0);

    let room_a = ConversationLocator::new(TEST_PLATFORM, "room-a");
    let room_b = ConversationLocator::new(TEST_PLATFORM, "room-b");
    let model = ScriptedModel::new([
        Completion::Reply("noted".to_owned()),
        Completion::Reply("ok".to_owned()),
        Completion::Reply("checkpointed".to_owned()),
    ]);
    server
        .platform()
        .route_message(
            &model,
            &room_a,
            &PersonId::new(TEST_PLATFORM, "dave"),
            SUBSTANTIVE,
            &[PersonId::new(TEST_PLATFORM, "dave")],
        )
        .await
        .unwrap();

    // Substance and cooldown pass, but room A is the only live conversation — the tail's only reader
    // is room A itself, which already has it in the buffer, so the audience gate alone blocks.
    assert_eq!(
        server
            .checkpoint_live_sessions(&model, CheckpointTrigger::Timer)
            .await
            .unwrap(),
        0
    );

    // Another conversation coming live gives the flush a reader; the same sweep now flushes room A
    // (room B's own delta stays under the substance threshold).
    server
        .platform()
        .route_message(
            &model,
            &room_b,
            &PersonId::new(TEST_PLATFORM, "erin"),
            "hi",
            &[PersonId::new(TEST_PLATFORM, "erin")],
        )
        .await
        .unwrap();
    assert_eq!(
        server
            .checkpoint_live_sessions(&model, CheckpointTrigger::Timer)
            .await
            .unwrap(),
        1
    );
}

#[tokio::test]
async fn a_checkpoint_flush_leaves_the_session_open_and_rides_the_buffer() {
    let (server, _clock) = born_agent();
    tune_checkpoint(&server, 30, 0);

    let room_a = ConversationLocator::new(TEST_PLATFORM, "room-a");
    let room_b = ConversationLocator::new(TEST_PLATFORM, "room-b");
    let model = ScriptedModel::new([
        Completion::Reply("noted".to_owned()),
        Completion::Reply("ok".to_owned()),
        // The checkpoint flush writes durable state and confirms.
        run_lua_call(r#"memory.create("topic/launch", "The migration ships on Friday")"#),
        Completion::Reply("saved what matters".to_owned()),
        Completion::Reply("indeed".to_owned()),
    ]);
    server
        .platform()
        .route_message(
            &model,
            &room_a,
            &PersonId::new(TEST_PLATFORM, "dave"),
            SUBSTANTIVE,
            &[PersonId::new(TEST_PLATFORM, "dave")],
        )
        .await
        .unwrap();
    server
        .platform()
        .route_message(
            &model,
            &room_b,
            &PersonId::new(TEST_PLATFORM, "erin"),
            "hi",
            &[PersonId::new(TEST_PLATFORM, "erin")],
        )
        .await
        .unwrap();
    assert_eq!(
        server
            .checkpoint_live_sessions(&model, CheckpointTrigger::Timer)
            .await
            .unwrap(),
        1
    );

    // The flush turn landed with the Flush provenance, and the session is still open: no
    // SessionEnded, and the next message continues the same session rather than opening a new one.
    let events = server.control().events().unwrap();
    let flush_turns = events
        .iter()
        .filter(|event| {
            matches!(
                &event.payload,
                EventPayload::ConversationTurn { produced_by: Some(produced), .. }
                    if produced.template_name == PromptTemplateName::Flush
            )
        })
        .count();
    assert_eq!(flush_turns, 1);
    assert!(
        !events
            .iter()
            .any(|event| matches!(event.payload, EventPayload::SessionEnded { .. })),
        "the checkpoint must leave every session open"
    );

    server
        .platform()
        .route_message(
            &model,
            &room_a,
            &PersonId::new(TEST_PLATFORM, "dave"),
            "sounds right?",
            &[PersonId::new(TEST_PLATFORM, "dave")],
        )
        .await
        .unwrap();
    assert_eq!(server.control().sessions(&room_a).unwrap().len(), 1);
    // The next turn's prompt replays the flush turn — its Lua step and its confirmation — like any
    // agent turn in the buffer (no rewind).
    let seen = model.recorded_messages();
    let last_prompt = seen.last().unwrap();
    assert!(
        last_prompt
            .iter()
            .any(|message| message.content.contains("saved what matters")),
        "the flush turn should ride the live buffer; prompt was: {last_prompt:?}"
    );
}

#[tokio::test]
async fn a_second_checkpoint_covers_only_the_delta_past_the_first() {
    let (server, _clock) = born_agent();
    tune_checkpoint(&server, 30, 0);

    let room_a = ConversationLocator::new(TEST_PLATFORM, "room-a");
    let room_b = ConversationLocator::new(TEST_PLATFORM, "room-b");
    let model = ScriptedModel::new([
        // Call 0: room A's first exchange, carrying the ALPHA marker.
        Completion::Reply("ok one".to_owned()),
        // Call 1: room B (the audience).
        Completion::Reply("ok".to_owned()),
        // Call 2: the first checkpoint flush.
        Completion::Reply("first checkpoint".to_owned()),
        // Call 3: room A's second exchange, carrying the BETA marker.
        Completion::Reply("ok two".to_owned()),
        // Call 4: the second checkpoint flush.
        Completion::Reply("second checkpoint".to_owned()),
    ]);
    server
        .platform()
        .route_message(
            &model,
            &room_a,
            &PersonId::new(TEST_PLATFORM, "dave"),
            "ALPHA: the migration plan is locked, we ship the database cutover on Friday.",
            &[PersonId::new(TEST_PLATFORM, "dave")],
        )
        .await
        .unwrap();
    server
        .platform()
        .route_message(
            &model,
            &room_b,
            &PersonId::new(TEST_PLATFORM, "erin"),
            "hi",
            &[PersonId::new(TEST_PLATFORM, "erin")],
        )
        .await
        .unwrap();
    assert_eq!(
        server
            .checkpoint_live_sessions(&model, CheckpointTrigger::Timer)
            .await
            .unwrap(),
        1
    );

    server
        .platform()
        .route_message(
            &model,
            &room_a,
            &PersonId::new(TEST_PLATFORM, "dave"),
            "BETA: after the cutover, Erin owns the comms and the fallback window is Monday.",
            &[PersonId::new(TEST_PLATFORM, "dave")],
        )
        .await
        .unwrap();
    assert_eq!(
        server
            .checkpoint_live_sessions(&model, CheckpointTrigger::Timer)
            .await
            .unwrap(),
        1
    );

    let seen = model.recorded_messages();
    assert_eq!(seen.len(), 5);
    // The first flush prompt covers the session so far (the ALPHA exchange).
    let first_flush: Vec<&str> = seen[2].iter().map(|m| m.content.as_str()).collect();
    assert!(
        first_flush.iter().any(|content| content.contains("ALPHA")),
        "the first checkpoint should see the pre-watermark turns: {first_flush:?}"
    );
    // The second covers only the delta past the first's watermark: BETA is in, ALPHA is not — a
    // repeat checkpoint never re-flushes the same turns.
    let second_flush: Vec<&str> = seen[4].iter().map(|m| m.content.as_str()).collect();
    assert!(
        second_flush.iter().any(|content| content.contains("BETA")),
        "the second checkpoint should see the new delta: {second_flush:?}"
    );
    assert!(
        !second_flush.iter().any(|content| content.contains("ALPHA")),
        "the second checkpoint must not re-flush turns before its watermark: {second_flush:?}"
    );
}
