/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_replica_free: (a: number, b: number) => void;
export const replica_conversations: (a: number) => [number, number, number];
export const replica_eventCount: (a: number) => number;
export const replica_foldTo: (a: number, b: number) => [number, number];
export const replica_foldedSeq: (a: number) => number;
export const replica_headSeq: (a: number) => number;
export const replica_memories: (a: number, b: number, c: number) => [number, number, number];
export const replica_memory: (a: number, b: number, c: number) => [number, number, number];
export const replica_new: (a: number, b: number) => [number, number, number];
export const replica_relations: (a: number) => [number, number, number];
export const replica_tags: (a: number) => [number, number, number];
export const rust_sqlite_wasm_abort: () => void;
export const rust_sqlite_wasm_assert_fail: (a: number, b: number, c: number, d: number) => void;
export const rust_sqlite_wasm_calloc: (a: number, b: number) => number;
export const rust_sqlite_wasm_free: (a: number) => void;
export const rust_sqlite_wasm_getentropy: (a: number, b: number) => number;
export const rust_sqlite_wasm_localtime: (a: number) => number;
export const rust_sqlite_wasm_malloc: (a: number) => number;
export const rust_sqlite_wasm_realloc: (a: number, b: number) => number;
export const sqlite3_os_end: () => number;
export const sqlite3_os_init: () => number;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_start: () => void;
