// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Stat } from "./Stat";
import type { TokenStat } from "./TokenStat";

/**
 * A scenario's aggregate across its N runs.
 */
export type Aggregate = { runs: number, 
/**
 * The pass rate over the runs (1.0 = every run passed every oracle of its bar).
 */
rate: number, 
/**
 * True iff every gating oracle held in every run (the safety invariant; drives the exit code).
 */
gating_passed: boolean, 
/**
 * The per-run drive wall-clock distribution (the truthful cost; see [`RunMetrics::wall_clock_ms`]).
 */
wall_clock_ms: Stat, latency_ms: Stat, tokens: TokenStat, steps_mean: number, };
