// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EntryId } from "./EntryId";

/**
 * How a [`EventPayload::BeliefArbitrated`] was resolved: which competing entries the agent credited
 * (by `EntryId`) and the one-line reconciling statement it wrote (spec §Write path → arbitration).
 */
export type ArbitrationResolution = { credited: Array<EntryId>, statement: string, };
