// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How a scenario's runs are judged (spec §Validation → gating versus measurement). A `Gating` bar is a
 * must-not-surface safety oracle — one regression across N fails the harness. A `Metric` bar is a
 * should-mark/should-surface rate that is reported against `threshold` but never fails the run.
 */
export type Bar = { "kind": "gating" } | { "kind": "metric", threshold: number, };
