// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Brief composition: what enters each brief, and how many participants get one.
 */
export type BriefSettings = { token_budget: bigint, recent_facts: bigint, present_set_cap: bigint, 
/**
 * How far ahead the `<upcoming/>` block looks, in days.
 */
upcoming_window_days: bigint, 
/**
 * The most upcoming items the `<upcoming/>` block lists.
 */
max_upcoming_items: bigint, };
