// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How much of a model call's request the model-interaction record stores (spec §Observability). The
 * deliberation — reasoning, finish reason, usage, latency — is captured at every level above `Off`.
 */
export type CaptureLevel = "Full" | "Digest" | "Off";
