// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A relation endpoint's cardinality. `One` means a memory has at most one link of this relation
 * in that direction (enforcement of the replace-on-`One` rule is the Lua layer's, Stage 4).
 */
export type Cardinality = "One" | "Many";
