// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The scenario families. Descriptive groupings for the viewer; the set grows over time.
 */
export type Category = "recall" | "tagging" | "relations" | "scheduling" | "privacy" | "compaction" | "arbitration" | "description";
