// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A calendar day as an ISO `YYYY-MM-DD` string. A day is not an instant: keeping the civil date
 * preserves "render it as a day" and lets the materializer derive its noon and day bounds.
 */
export type CivilDate = string;
