// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ToolCall } from "./ToolCall";

/**
 * A single step's outcome: the model either calls tools or produces a final reply, never both in
 * one step (spec §Agent loop), or it ends the turn silently — a first-class outcome, distinct
 * from an empty reply, for messages not addressed to the agent.
 */
export type Completion = { "ToolCalls": Array<ToolCall> } | { "Reply": string } | "Silent";
