// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Concurrency limits (spec §Concurrency): how many conversation streams may run at once. The shared
 * local model is the binding constraint, so this caps concurrent turns rather than letting unbounded
 * streams crowd the model. Read when the server is constructed, so a change takes effect on restart.
 */
export type ConcurrencySettings = { 
/**
 * The most conversation turns that may be in flight at once; further streams queue for a slot.
 */
max_concurrent_streams: number, };
