// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The stable address of a durable conversation on a platform — what a platform client reports so
 * the server resolves it to the same [`ConversationId`] every time. `platform` is a short config
 * key (`direct`, `discord`, `slack`); `scope_path` locates the room within it (a channel id, a DM
 * thread). Two locators name the same room exactly when both fields match.
 */
export type ConversationLocator = { platform: string, scope_path: string, };
