// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A durable conversation (a room the agent meets again and again), keyed by its
 * [`ConversationLocator`] and persisting across sessions for the agent's life.
 */
export type ConversationId = string;
