// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The stable, globally-unique identity of a single content entry — addressable for supersession,
 * arbitration references, and per-entry vectors.
 */
export type EntryId = string;
