// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RunMeta } from "./RunMeta";
import type { ScenarioReport } from "./ScenarioReport";

/**
 * One eval run over the whole scenario suite.
 */
export type EvalPackage = { meta: RunMeta, scenarios: Array<ScenarioReport>, };
