// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Provenance for events that carry an authority, distinct from a participant teller: `Bootstrap`
 * for genesis, `Orchestration` for prompt templates, `Operator` for operator/control writes, and
 * `Agent` for the agent's own (spec §Initialization, §Trust model).
 */
export type EventSource = "Bootstrap" | "Agent" | "Operator" | "Orchestration";
