// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EventPayload } from "./EventPayload";
import type { Seq } from "./Seq";
import type { Timestamp } from "./Timestamp";

/**
 * A committed event: a payload assigned a position in the log's total order and stamped with the
 * wall-clock time it was recorded. This is what a read returns; it is immutable. Serializable so it
 * rides verbatim in an eval package and (later) over the console's wire (spec §Observability).
 */
export type Event = { seq: Seq, recorded_at: Timestamp, payload: EventPayload, };
