// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A relation the link-inference pass coins for a relationship no registered relation fits, recorded
 * on the `LinksInferred` audit event so the model's reasoning is replayable. Mirrors the agent
 * crate's `NewRelationSpec`, defined here so the core event type does not depend on the agent crate.
 */
export type InferredRelationSpec = { name: string, inverse: string, from_card: string, to_card: string, symmetric: boolean, reflexive: boolean, };
