// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A relationship the link-inference pass identified, recorded on the `LinksInferred` audit event.
 * Mirrors the agent crate's `InferredLink`, defined here so the core event type does not depend on
 * the agent crate.
 */
export type InferredLinkSpec = { 
/**
 * The statement number (1-based) the model cited as grounding this relationship.
 */
entry: number, relation: string, target: string, 
/**
 * "to" (subject → target) or "from" (target → subject).
 */
direction: string, };
