// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Whether a turn is the agent responding to a message or acting unprompted (spec §Time).
 */
export type Initiation = "Responding" | "Initiated";
