// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Who authored a link: the agent itself, an operator acting through the console, the
 * merge-adjudication pass that accepted an agent's cross-platform proposal on the evidence, or the
 * off-hot-path link-inference pass that extracted a relationship implicit in memory content.
 * `Adjudicated` is the one path past the operator-only merge gate, distinguishable in the log so an
 * audit can tell a console merge from an adjudicated one (spec §Cross-platform identity); `Inferred`
 * marks links the background pass authored without a teller behind them (spec §Write path → link
 * inference).
 */
export type LinkSource = "Agent" | "Operator" | "Adjudicated" | "Inferred";
