// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Who authored a link: the agent itself, or an operator acting through the console.
 */
export type LinkSource = "Agent" | "Operator";
