// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InferredLinkSpec } from "./InferredLinkSpec";
import type { InferredRelationSpec } from "./InferredRelationSpec";

/**
 * The link-inference pass's parsed result for one memory: the new relations it proposed and the
 * links it identified, carried on the `LinksInferred` event so the model's deliberation is visible
 * in the log (spec §Write path → link inference). An empty result is recorded too — a pass that
 * found no relationships is as diagnostic as one that found the wrong ones.
 */
export type LinkInferenceResult = { new_relations: Array<InferredRelationSpec>, links: Array<InferredLinkSpec>, };
