// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Who authored a link: the agent itself, an operator acting through the console, or — for a
 * cross-platform `same_as` only — the merge-adjudication pass that accepted an agent's proposal on
 * the evidence. `Adjudicated` is the one path past the operator-only merge gate, distinguishable in
 * the log so an audit can tell a console merge from an adjudicated one (spec §Cross-platform identity).
 */
export type LinkSource = "Agent" | "Operator" | "Adjudicated";
