// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Aggregate } from "./Aggregate";
import type { Event } from "./Event";
import type { RunMeta } from "./RunMeta";
import type { RunRecord } from "./RunRecord";
import type { ScenarioMeta } from "./ScenarioMeta";

/**
 * One event in an eval run's live log. Emitted in order; the console folds the sequence into an
 * [`EvalPackage`], and the harness persists it as a `.jsonl` sidecar.
 */
export type LiveEvent = { "kind": "manifest", meta: RunMeta, scenarios: Array<ScenarioMeta>, } | { "kind": "run_started", scenario: number, run: number, } | { "kind": "run_event", scenario: number, run: number, event: Event, } | { "kind": "run_completed", scenario: number, run: number, record: RunRecord, aggregate: Aggregate, } | { "kind": "finished", finished_at_ms: number, };
