// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A memory's agent-facing handle, namespaced by kind (e.g. `person/dave`, `topic/climbing`).
 */
export type MemoryName = string;
