// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The canonical, immutable, internal identity of a memory.
 */
export type MemoryId = string;
