// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Role } from "./Role";
import type { ToolCall } from "./ToolCall";

/**
 * A message in the conversation handed to the model. `tool_calls` is populated on an assistant
 * message that called tools; `tool_call_id` ties a tool-result message to the call it answers —
 * the threading the OpenAI protocol needs across multi-step tool use.
 */
export type Message = { role: Role, content: string, tool_calls: Array<ToolCall>, tool_call_id: string | null, };
