// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which model call within a turn a [`EventPayload::ModelCalled`] records: a step of the agent loop,
 * or the post-turn description synthesis (spec §Observability). Paired with `turn_id`, it groups a
 * phase's calls so the prompt can be reconstructed from the [`RequestRecord`] deltas.
 */
export type ModelPhase = "Step" | "Synthesis";
