// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CaptureLevel } from "./CaptureLevel";

/**
 * Observability (spec §Observability): how much of each model call the model-interaction record
 * captures. The full request repeats the agent loop's growing buffer (delta-encoded, but still
 * material at the `Base` of each turn), so the verbosity is operator-tunable at runtime.
 */
export type ObservabilitySettings = { 
/**
 * How much of each model call to record (the deliberation is always captured; this governs the
 * request side).
 */
capture_model_calls: CaptureLevel, };
