// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PromptTemplateName } from "./PromptTemplateName";

/**
 * Provenance for an event produced by model inference: the model and the prompt template (by name
 * and version) that wrote it (spec §Storage → provenance on inference). Carried by inference events
 * so "which model and template produced this" is answerable, and so regenerative replay knows what
 * to re-run; purely mechanical events leave it `None`.
 */
export type ProducedBy = { model_id: string, template_name: PromptTemplateName, template_version: number, };
