// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The orchestration prompt templates the build ships — a closed, build-defined set (spec
 * §Initialization → prompt templates). Serialized in kebab-case to match the human-facing names.
 */
export type PromptTemplateName = "scaffold" | "description-regen" | "temporal-extraction" | "flush" | "imprint" | "merge-adjudication" | "link-inference";
