// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TauDays } from "./TauDays";

/**
 * The recency bonus and its volatility-dependent decay constant.
 */
export type RecencySettings = { 
/**
 * Maximum recency contribution (at zero age).
 */
bonus: number, 
/**
 * Decay time constant in days, by the memory's volatility.
 */
tau_days: TauDays, };
