// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Message } from "./Message";
import type { ToolChoice } from "./ToolChoice";
import type { ToolSpec } from "./ToolSpec";

/**
 * The request side of a model-interaction record, stored as a delta so the agent loop's growing
 * message buffer is not repeated in full on every step (spec §Observability). A turn's phase sends
 * a frozen request shape (`system`, `tools`, `tool_choice`, `thinking`) over an append-only message
 * buffer, so the first call records a [`RequestRecord::Base`] and each later call records only the
 * messages appended since the previous one. The full prompt for any call is reconstructed by taking
 * the `Base` of its `(turn_id, phase)` group, then concatenating the `Continuation` deltas in `seq`
 * order; the frozen fields come from the `Base`.
 */
export type RequestRecord = { "Base": { system: string, messages: Array<Message>, tools: Array<ToolSpec>, tool_choice: ToolChoice, thinking: boolean | null, } } | { "Continuation": { appended_messages: Array<Message>, } };
