// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * An RFC-5545 recurrence rule, stored verbatim. The denormalization here leaves it sort-null (no
 * fixed instant); a supported subset (`FREQ` + `INTERVAL`) is interpreted by [`super::next_occurrence`]
 * when the scheduler and calendar need concrete instances.
 */
export type Rrule = string;
