// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Per-run measurements, summed from the run's `ModelCalled` events.
 */
export type RunMetrics = { model_calls: number, steps: number, 
/**
 * The run's actual wall-clock to drive (turns plus the synchronous catch-ups it forces). The
 * truthful cost: unlike `total_latency_ms`, it includes work that records no `ModelCalled` — the
 * background describer's synthesis, run synchronously in the harness.
 */
wall_clock_ms: number, 
/**
 * Summed `ModelCalled` duration. Conversational model calls only — off-hot-path synthesis records
 * no `ModelCalled`, so this undercounts total compute; read `wall_clock_ms` for that.
 */
total_latency_ms: number, prompt_tokens: number, completion_tokens: number, total_tokens: number, 
/**
 * Whether every gating oracle in this run passed.
 */
gating_passed: boolean, };
