// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What produced this package: the harness, the models, and the wall-clock span.
 */
export type RunMeta = { harness_version: string, 
/**
 * The repository commit the harness ran at, when resolvable.
 */
git_sha: string | null, model_id: string, embedding_model: string | null, 
/**
 * Epoch milliseconds.
 */
started_at_ms: number, finished_at_ms: number, runs_per_scenario: number, concurrency: number, };
