// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Event } from "./Event";
import type { RunMetrics } from "./RunMetrics";
import type { Verdict } from "./Verdict";

/**
 * One run: the run's whole event log (the deliberation and resulting state the viewer reconstructs),
 * its verdicts, and the metrics computed from its `ModelCalled` events.
 */
export type RunRecord = { index: number, events: Array<Event>, verdicts: Array<Verdict>, metrics: RunMetrics, };
