// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Aggregate } from "./Aggregate";
import type { RunRecord } from "./RunRecord";
import type { ScenarioMeta } from "./ScenarioMeta";

/**
 * One scenario's N runs plus their aggregate.
 */
export type ScenarioReport = { meta: ScenarioMeta, runs: Array<RunRecord>, aggregate: Aggregate, };
