// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Bar } from "./Bar";
import type { Category } from "./Category";

/**
 * A scenario's identity and its bar — the rubric the aggregate is read against.
 */
export type ScenarioMeta = { name: string, category: Category, description: string, bar: Bar, };
