// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Scheduled-work delivery: the drained wake-up surface (spec §Agent-initiated speech).
 */
export type SchedulerSettings = { 
/**
 * The most fired wake-ups a single session-open drain raises.
 */
max_wakeups_per_session: bigint, 
/**
 * How often the background scheduler driver fires due wake-ups, in seconds (spec §Scheduled work).
 * Read by the serving host at startup, so a change takes effect on restart.
 */
tick_seconds: bigint, };
