// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RecencySettings } from "./RecencySettings";

/**
 * Multi-signal search scoring (spec §Time → search scoring): the blend weights and the recency
 * decay.
 */
export type SearchSettings = { cosine: number, bm25: number, tag: number, recency: RecencySettings, };
