// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A position in the event log's single total order. The first event is `Seq(1)`; `Seq::ZERO`
 * denotes "before any event" and is the lower bound for a full read.
 */
export type Seq = number;
