// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One bounded activity window within a conversation — the unit that freezes a brief and anchors the
 * prefix cache. Opens on first activity (or resumption after a quiet gap, or a compaction
 * re-segment) and closes on idle (spec §Conversations).
 */
export type SessionId = string;
