// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BriefSettings } from "./BriefSettings";
import type { CompactionSettings } from "./CompactionSettings";
import type { ConcurrencySettings } from "./ConcurrencySettings";
import type { ObservabilitySettings } from "./ObservabilitySettings";
import type { SchedulerSettings } from "./SchedulerSettings";
import type { SearchSettings } from "./SearchSettings";
import type { TurnSettings } from "./TurnSettings";

/**
 * The agent's behavioral tunables, grouped by the subsystem each shapes. [`Default`] is the spec's
 * starting values (each substruct carries its own).
 */
export type Settings = { compaction: CompactionSettings, brief: BriefSettings, turn: TurnSettings, search: SearchSettings, scheduler: SchedulerSettings, concurrency: ConcurrencySettings, observability: ObservabilitySettings, };
