// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A latency distribution across runs (milliseconds).
 */
export type Stat = { p50: number, p95: number, mean: number, };
