// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The recency decay constant (in days) for each [`Volatility`](crate::event::Volatility) level.
 */
export type TauDays = { high: number, medium: number, low: number, };
