// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MemoryId } from "./MemoryId";

/**
 * Who told the agent a piece of content (spec §Visibility). Distinct from [`EventSource`], which is
 * authorship *authority*: `told_by` is the *teller* whose confidence the read-time predicate
 * reasons about.
 */
export type Teller = { "Participant": MemoryId } | "Agent" | "Bootstrap";
