// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CivilDate } from "./CivilDate";
import type { Direction } from "./Direction";
import type { MemoryName } from "./MemoryName";
import type { Rrule } from "./Rrule";
import type { Timestamp } from "./Timestamp";

/**
 * A typed, vague-capable reference to when a fact occurred (spec §Time → bi-temporality). Stored as
 * tagged JSON in the `occurred_at` column; the materializer derives `occurred_sort`/`occurred_lo`/
 * `occurred_hi` from it via [`TemporalRef::bounds`].
 *
 * The agent writes it as a tagged Lua table whose single key names the variant:
 * `{ instant = <ms> }`, `{ day = "YYYY-MM-DD" }`, `{ range = { start = <ms>, end = <ms> } }`,
 * `{ approx = { center = <ms>, fuzz_days = <n> } }`, `{ recurring = "<rrule>" }`, or
 * `{ before_after = { dir = "before" | "after", anchor = "event/..." } }`. Natural-language phrases
 * ("last week") are resolved to this type by a later increment's extraction pass, not here.
 */
export type TemporalRef = { "instant": Timestamp } | { "day": CivilDate } | { "range": { start: Timestamp, end: Timestamp, } } | { "approx": { center: Timestamp, fuzz_days: number, } } | { "recurring": Rrule } | { "before_after": { dir: Direction, anchor: MemoryName, } };
