// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How a Lua block ended when the agent saw the outcome (spec §Event sourcing). A block that
 * commits normally has no terminal cause; one the agent observed failing or deliberately aborting
 * records why.
 */
export type TerminalCause = { "Error": string } | { "Aborted": string };
