// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Wall-clock time as milliseconds since the Unix epoch, UTC. A denormalized convenience for
 * human-readable queries and recency math; `Seq` is the authoritative timeline, and `Seq` breaks
 * ties (see spec §Time → sequence vs wall-clock).
 */
export type Timestamp = number;
