// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Mean token usage across runs.
 */
export type TokenStat = { prompt_mean: number, completion_mean: number, total_mean: number, };
