// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One structured tool call emitted by the model. `arguments` is JSON, parsed by the caller.
 */
export type ToolCall = { id: string, name: string, arguments: string, };
