// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How the model may use the available tools. `Auto` lets it choose between a tool call and a reply
 * (the agent loop); `Required` forces it to call a tool, used to coerce structured output — e.g.
 * description regeneration forces a single `describe` tool so the answer can't drift into prose.
 */
export type ToolChoice = "Auto" | "Required";
