// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A tool the model may call: its name, a description, and a JSON-Schema for its arguments, sent to
 * the model so it produces well-formed calls.
 */
export type ToolSpec = { name: string, description: string, parameters: any, };
