// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The author of a conversation turn (spec §Event sourcing → ConversationTurn). The participant and
 * session bindings arrive with the conversation machinery at Stage 8.
 */
export type TurnRole = "Participant" | "Agent" | "System";
