// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One run of the agent loop — a whole response cycle, producing exactly one `role = agent`
 * turn. A block's buffered side effects and its `LuaExecuted` share their turn's id.
 */
export type TurnId = string;
