// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The agent step loop.
 */
export type TurnSettings = { 
/**
 * Per-turn step bound; hitting it ends the turn with a surfaced error.
 */
max_steps: number, 
/**
 * Per-block duration budget (spec §Concurrency → lock acquisition): a block held longer than this —
 * stuck on slow external I/O or a lock-wait — aborts, emitting nothing. Set generously, above a
 * single MCP call's own timeout, so an ordinary multi-call block is never cut.
 */
block_timeout_seconds: number, 
/**
 * How many times a block that times out on a lock-wait (with no MCP call) is re-run before giving
 * up with a terminal error (spec §Concurrency → timeout-and-retry). A block that has made an MCP
 * call is never retried, regardless of this bound.
 */
max_block_attempts: number, };
