// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The token accounting the serving layer reports for a generation. Fields are `Option` because not
 * every backend returns usage and the scripted fake may decline to script it; an absent
 * `prompt_tokens` makes the compaction trigger fall back to a deterministic estimate over the
 * buffer (spec §Compaction). `prompt_tokens` measures the whole prompt — the frozen prefix plus the
 * live buffer — which is exactly the surface the buffer budget bounds. `completion_tokens` and
 * `total_tokens` are recorded for observability (the model-interaction record) but do not drive the
 * compaction trigger.
 */
export type Usage = { prompt_tokens: number | null, completion_tokens: number | null, total_tokens: number | null, };
