// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Whether a verdict is a gating safety oracle or a reported quality metric.
 */
export type VerdictKind = "oracle" | "metric";
