// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { VerdictKind } from "./VerdictKind";

/**
 * One oracle's outcome for a run. `judge_raw` carries the judge model's verbatim response when a
 * criterion was judged (rather than checked deterministically), so the matcher stays reviewable.
 */
export type Verdict = { criterion: string, kind: VerdictKind, passed: boolean, rationale: string, judge_raw: string | null, };
