// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MemoryId } from "./MemoryId";

/**
 * How widely a content entry may be surfaced (spec §Visibility). The read-time predicate
 * `visible(...)` interprets these against the present set; `PrivateToTeller` additionally never
 * surfaces to the subject of a person memory.
 */
export type Visibility = "Public" | "PrivateToTeller" | { "Exclude": Array<MemoryId> };
