// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How sharply a memory's facts decay in search ranking (spec §Data model). Defaults to `Medium`.
 */
export type Volatility = "Low" | "Medium" | "High";
