//! The export pipeline: ts-rs type export, console constants, and settings metadata generation.
//!
//! The settings metadata is extracted at compile time by the `SettingsMetadata` derive (a
//! proc-macro in `crates/settings-metadata-derive`), which reads the `///` doc comments and field
//! names directly from the token stream. No rustdoc JSON, no nightly toolchain, no Node script.

use std::path::Path;

use anyhow::{Context, Result};
use zuihitsu_core::settings_metadata::{SettingsField, SettingsMetadata};

/// Export all TypeScript wire-contract types to `dir`, write the Rust constants the console consumes
/// as runtime values, and generate the settings metadata from the `SettingsMetadata` derive. This is
/// the body of the `export-types` binary.
pub fn export_types(dir: &Path) -> Result<()> {
    use ts_rs::TS;

    use crate::{
        agent::{BackendHealth, CircuitState},
        live::LiveEvent,
        package::{EvalPackage, PackageSummary},
    };
    use zuihitsu_connector_types::{PlatformResponse, StreamFrame, TurnOutcome};
    use zuihitsu_core::{
        ids::{Namespace, NamespacedMemoryName},
        progress::TurnProgress,
        settings::{
            BriefSettings, CompactionSettings, ConcurrencySettings, ObservabilitySettings,
            RecencySettings, SchedulerSettings, SearchSettings, TauDays, TurnSettings,
        },
    };

    EvalPackage::export_all_to(dir).context("exporting EvalPackage")?;
    PackageSummary::export_all_to(dir).context("exporting PackageSummary")?;
    LiveEvent::export_all_to(dir).context("exporting LiveEvent")?;
    Namespace::export_all_to(dir).context("exporting Namespace")?;
    NamespacedMemoryName::export_all_to(dir).context("exporting NamespacedMemoryName")?;
    TurnOutcome::export_all_to(dir).context("exporting TurnOutcome")?;
    PlatformResponse::export_all_to(dir).context("exporting PlatformResponse")?;
    StreamFrame::export_all_to(dir).context("exporting StreamFrame")?;
    BackendHealth::export_all_to(dir).context("exporting BackendHealth")?;
    CircuitState::export_all_to(dir).context("exporting CircuitState")?;
    TurnProgress::export_all_to(dir).context("exporting TurnProgress")?;
    write_console_constants(dir).context("writing console constants")?;

    // Collect settings metadata from every settings struct via the `SettingsMetadata` derive.
    let mut entries: Vec<SettingsField> = Vec::new();
    entries.extend(CompactionSettings::fields());
    entries.extend(BriefSettings::fields());
    entries.extend(TurnSettings::fields());
    entries.extend(ConcurrencySettings::fields());
    entries.extend(ObservabilitySettings::fields());
    entries.extend(SearchSettings::fields());
    entries.extend(RecencySettings::fields());
    entries.extend(TauDays::fields());
    entries.extend(SchedulerSettings::fields());
    // Stable, human-readable ordering: by the dotted path.
    entries.sort_by(|a, b| a.path.cmp(&b.path));

    let contents = render_settings_metadata_ts(&entries);
    std::fs::write(dir.join("settings-metadata.ts"), contents)
        .context("writing settings-metadata.ts")?;

    println!(
        "exported the eval-package and live-event types, the console constants, and the settings \
         metadata ({} fields), to {}",
        entries.len(),
        dir.display()
    );
    Ok(())
}

/// Emit the Rust constants the console needs as runtime *values* (ts-rs exports types, not consts),
/// so Rust stays the single source of truth for values that are load-bearing on both sides. Today
/// that is the `DIRECT_PLATFORM` key: identity resolution merges an arrival on it under operator
/// authority (spec §Cross-platform identity), and the console builds its own room locators with it —
/// a drift between the two would silently break that reconciliation.
fn write_console_constants(dir: &Path) -> Result<()> {
    use zuihitsu_core::ids::DIRECT_PLATFORM;
    let contents = format!(
        "// Generated by `cargo build -p zuihitsu` — do not edit. Rust constants the console consumes \
         as values.\n\n\
         /// The platform key for the operator's own direct interface (Rust `ids::DIRECT_PLATFORM`).\n\
         export const DIRECT_PLATFORM = {:?};\n",
        DIRECT_PLATFORM,
    );
    std::fs::write(dir.join("constants.ts"), contents).context("writing constants.ts")
}

// ---------------------------------------------------------------------------
// Settings metadata rendering
// ---------------------------------------------------------------------------

/// Field-name suffix → unit. Order matters: more specific suffixes (e.g. `_char_budget`) must come
/// before shorter ones (e.g. `_budget`) so they match first.
const SUFFIX_UNITS: &[(&str, &str)] = &[
    ("_seconds", "seconds"),
    ("_days", "days"),
    ("_char_budget", "chars"),
    ("_budget", "tokens"),
    ("_turns", "turns"),
    ("_steps", "steps"),
    ("_items", "items"),
    ("_facts", "facts"),
    ("_cap", "items"),
    ("_attempts", "attempts"),
];

/// Field names whose unit does not follow the suffix convention. Looked up before the suffix table.
const EXPLICIT_UNITS: &[(&str, &str)] = &[
    ("max_wakeups_per_session", "wake-ups"),
    ("max_concurrent_streams", "streams"),
    ("capture_model_calls", ""),
    ("bonus", "weight"),
    ("cosine", "weight"),
    ("bm25", "weight"),
    ("tag", "weight"),
    ("high", "days"),
    ("medium", "days"),
    ("low", "days"),
];

/// The short label the editor renders after the input. Mirrors `unit` except for `_seconds`,
/// where the value is shown in minutes, so the suffix is `min` to match the displayed value.
fn display_unit(field_name: &str, unit: &str) -> String {
    if field_name.ends_with("_seconds") {
        "min".to_owned()
    } else {
        unit.to_owned()
    }
}

/// Infer the unit from the field name: first by explicit lookup, then by suffix matching.
fn unit_for(field_name: &str) -> String {
    if let Some(&(_, unit)) = EXPLICIT_UNITS.iter().find(|(n, _)| *n == field_name) {
        return unit.to_owned();
    }
    for (suffix, unit) in SUFFIX_UNITS {
        if field_name.ends_with(suffix) {
            return unit.to_string();
        }
    }
    String::new()
}

/// Extract the field name from the dotted path (the part after the last `.`).
fn field_name_from_path(path: &str) -> &str {
    path.rsplit('.').next().unwrap_or(path)
}

/// Render the settings metadata entries as a TypeScript file.
fn render_settings_metadata_ts(entries: &[SettingsField]) -> String {
    let mut lines = vec![
        "// Generated by `cargo build -p zuihitsu` from the zuihitsu-core settings derives. Do not edit.".to_string(),
        "// Rerun `cargo build -p zuihitsu` after a settings doc comment or schema change.".to_string(),
        String::new(),
        "export interface SettingsFieldMeta {".to_string(),
        "  description: string;".to_string(),
        "  unit: string;".to_string(),
        "  display: string;".to_string(),
        "}".to_string(),
        String::new(),
        "export const settingsMetadata: Record<string, SettingsFieldMeta> = {".to_string(),
    ];
    for entry in entries {
        let field_name = field_name_from_path(&entry.path);
        let unit = unit_for(field_name);
        let display = display_unit(field_name, &unit);
        let desc = serde_json::to_string(&entry.description).unwrap_or_default();
        let unit = serde_json::to_string(&unit).unwrap_or_default();
        let display = serde_json::to_string(&display).unwrap_or_default();
        let path = serde_json::to_string(&entry.path).unwrap_or_default();
        lines.push(format!(
            "  {path}: {{ description: {desc}, unit: {unit}, display: {display} }},"
        ));
    }
    lines.push("};".to_string());
    lines.push(String::new());
    lines.join("\n")
}
